### PR TITLE
Alternative approach to catch failing apps

### PR DESCRIPTION
**Pull request by alessandrothea**
Only using `sh.RunningProcess.is_alive` method

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
That was kinda what was there before.  
The Linux process was successfully running, but we were blind to the state of the Flask server within that process.  Pierre's model has the nice feature that we really, really know that the Flask server has reached the appropriate point in its lifecycle...

**Comment by bieryAtFnal** [comment]
Pierre and I also talked about a model in which we used the `psutil` package to interrogate the Flask Linux process to see if it is listening on the expected port.  That has the advantage of not generating an HTTP call, but i has the downside of adding a new package to our dependencies.

**Comment by plasorak** [comment]
Yes, I think this PR is a bit different though, this is for the applications rather than the flask server. It sometimes happens that the apps don't actually start at all when booting, and previously, we would need to wait until timeout to figure this out. I had done something here https://github.com/DUNE-DAQ/nanorc/blob/develop/src/nanorc/sshpm.py#L247 which wasn't very elegant, but would exit straight away.

**Comment by bieryAtFnal** [comment]
Ah, sorry, I was thinking that this PR was related to v2.0.11, but it seems like you are saying that it is related to v2.0.10.  Sorry for the noise.

**Pull request merged**
