### PR TITLE
FSM nodes

### PR DESCRIPTION
**Pull request by plasorak**
OK... I'm not particularly proud of this, but here we go. I'm running out of ideas to make this better. A couple of features:
 - `fsm.py` has a class that inherits from `transitions.Machine`, which turns all the nodes into FSMs with `add_node`
 - Once the nodes are FSMs, they get:
   - `is_<state>()`, where `<state>` can be booted, started,...
   - `<command>()` where `<command>` can be boot, start... this will use the FSM to issue transition (can't execute a start on non configured state etc)
   - `to_<command>()` which is like previous, BUT it won't check for the FSM state. So you _can_ do `to_start()` on non configured state. We can deactivate this (`auto_transition=False` in fsm.py), but it is convenient if we want to go on error state from anywhere (`to_error()`). 
   - `can_<command>()`, which I had to add myself, that returns a boolean whether a transition is allowed. It turns out that this could be useful if we don't want to get a new run number when we do `start` at the wrong moment. There are other way to do that, for example, we could use the `prepare` callbacks.
 - Under the hood, everything happens in `on_enter_<command>()`, which gets all the data passed with the event. This is bound in `ApplicationNode`, `SubsystemNode` and `GroupeNode` to do what we want (send to the application supervisor, send to children, etc...)
 - If an error is thrown, hopefully all the parent nodes go in `error` state and the user is duly reprimanded.
 - There is some message passing/response upon error, maybe this is useless, especially since I don't print them.

Happy to get comment on that!

### CODE REVIEW

**Comment by plasorak** [comment]
By the way, 0aed280 maybe a bit off topic.

**Comment by bieryAtFnal** [comment]
Pierre,
Something that I noticed is that I get the error message shown below when running various integration tests, when the DQM process is not included in the system configuration.  With the older _nanorc_, I would not see these complaints about _dqm0_ not being included in the system...

```
           INFO     /tmp/pytest-of-biery/pytest-288/json5 received command 'stop'                                                  groupnode.py:66
           INFO     /tmp/pytest-of-biery/pytest-288/json5 propagating to children nodes                                            groupnode.py:84
                    (['/tmp/pytest-of-biery/pytest-288/json5']) simultaneously                                                                    
           INFO     Sending stop to the subsystem /tmp/pytest-of-biery/pytest-288/json5, in the order: ['dqm0', 'hsi', 'ruemu0',       node.py:142
                    'trigger', 'dataflow0']                                                                                                       
           ERROR    node 'dqm0' is not a child of the subprocess "/tmp/pytest-of-biery/pytest-288/json5", check the order list for     node.py:219
                    command "stop"                                                                                                                
           INFO     Sending stop to hsi (http://mu2edaq14:3332)                                                                     appctrl.py:226
           INFO     Ack: <Response [202]>                                                                                           appctrl.py:234
[17:09:31] INFO     Received reply from hsi to stop                                                                                 appctrl.py:253
           INFO     Sending stop to ruemu0 (http://mu2edaq14:3335)                                                                  appctrl.py:226
           INFO     Ack: <Response [202]>                                                                                           appctrl.py:234
           INFO     Received reply from ruemu0 to stop                                                                              appctrl.py:253
           INFO     Sending stop to trigger (http://mu2edaq14:3333)                                                                 appctrl.py:226
           INFO     Ack: <Response [202]>                                                                                           appctrl.py:234
           INFO     Received reply from trigger to stop                                                                             appctrl.py:253
           INFO     Sending stop to dataflow0 (http://mu2edaq14:3334)                                                               appctrl.py:226
           INFO     Ack: <Response [202]>                                                                                           appctrl.py:234
           INFO     Received reply from dataflow0 to stop                                                                           appctrl.py:253
[17:09:31] Stopped run #101                                                                                                            core.py:204
```

**Comment by plasorak** [comment]
Yeah, I believe this is an "error" in the configuration, in the sense that if somebody specified a command order in the configuration JSON which included an application that doesn't exist, it will print this error. It shouldn't impact anything, as this app will be ignored, but nanorc now points it out.

**Comment by bieryAtFnal** [comment]
That sounds good.  I've often felt uncomfortable when configurations have included transition commands for a given DAQ process even though that DAQ process is not part of the system configuration.  So, these complaints from nanorc will help us notice those issues and clean them up.
My only testing so far has been to use this branch of nanorc when running integration tests, and I haven't noticed any problems so far.

**Pull request merged**
