### PR TITLE
fixed warning message when terminating nanorc correctly

### PR DESCRIPTION
**Pull request by carloschavez**
Getting rid of the  warning message when nanorc is  terminating correctly.

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
Hi Carlos,
I'm going to modify a few of the "project"-related fields in this Issue so that it shows up in the appropriate Tracking Project Views.  This shouldn't affect anything about the normal steps that you would take with this PR.
Kurt

**Comment by plasorak** [comment]
Hi Carlos, could you do the same modification at:
https://github.com/DUNE-DAQ/nanorc/blob/carloschavez/warning_message_fix/src/nanorc/__main_np04__.py#L99
and 
https://github.com/DUNE-DAQ/nanorc/blob/carloschavez/warning_message_fix/src/nanorc/__main_timing__.py#L77
Thanks!

**Comment by carloschavez** [comment]
Hi Pierre,   I have included your request and tested the changes running nanotimingrc and nano04rc.

**Comment by plasorak** [comment]
Looks good to me and works like a charm, @bieryAtFnal, would you mind trying, or you trust us :)

**Pull request merged**
