### PR TITLE
Improved processing of environment variables

### PR DESCRIPTION
**Pull request by eflumerf**
Add double-quotes around exported environment variables to resolve Bash
warnings about parentheses.

Alter processing of getenv variables so that a default variable value
can be specified, and improve the error message that occurs when an
environment variable is requested that doesn't exist in the environment
and has no default.

### CODE REVIEW

**Comment by eflumerf** [comment]
I have tested this using the DUNE-DAQ/minidaqapp#63 configuration generation on 4 hosts, each had the TRACE_FILE default variable correctly substituted. ERS variables with parentheses did not cause issues launching processes, but I did not check throttle behavior.

**Comment by eflumerf** [comment]
Note: to test this, you have to:
1. Set up your daq area (dbt-workarea-env et. al.)
2. pushd dbt-pyenv/lib/python3.8/site_packages && rm -rf nanorc* && popd
3. git clone https://github.com/eflumerf/nanorc.git
4. cd nanorc && git checkout eflumerf/GetEnvWithDefault
5. python setup.py install
6. easy_install nanorc

**Comment by alessandrothea** [comment]
Hi @eflumerf,
the changes look OK to me. I'm merging this PR.
Note that installing an updated version of nanorc in the python environment can be done with one-liner:

```sh
pip install -U https://github.com/eflumerf/nanorc/archive/eflumerf/GetEnvWithDefault.zip
```
or, after the merge:

```sh
pip install -U https://github.com/DUNE-DAQ/nanorc/archive/master.zip
```

**Comment by bieryAtFnal** [comment]
Hi, I tried the two suggested 'pip install' commands above, and I got error messages like the following:

```
Collecting https://github.com/DUNE-DAQ/nanorc/archive/master.zip
  Downloading https://github.com/DUNE-DAQ/nanorc/archive/master.zip
     / 81kB 2.5MB/s
Collecting click (from nanorc==0.0.0)
  Using cached https://files.pythonhosted.org/packages/21/83/308a74ca1104fe1e3197d31693a7a2db67c2d4e668f20f43a2fca491f9f7/click-8.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    error in click setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zlEfvE/click/
You are using pip version 20.0.2, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by bieryAtFnal** [comment]
ah, sorry, needed to set up the work environment...

**Pull request merged**
